default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0

development:
  <<: *default
  database: ticketee_development

test:
  <<: *default
  database: ticketee_test

production:
  <<: *default
  database: ticketee_production
